### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by aybmab** [joaquimserafim/node-netcat#10]
I recently started getting the following error:

{ Error: read ECONNRESET
    at exports._errnoException (util.js:1007:11)
    at TCP.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

I've had this process running for a couple of months, and it just randomly started throwing these errors. Any idea why?

**Comment by joaquimserafim** [comment]
Hi, thank you for using node-netcat

are you not having downtimes  or some network issues?

Take care
