### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by futurist** [joaquimserafim/node-netcat#7]
I used the code below in server as app.js:

```
var NetcatServer = require('node-netcat').server;
var server = NetcatServer(81);

server.on('ready', function() {
    console.log('server ready');
});

server.on('data', function(client, data) {
    console.log('server rx: ' + data + ' from ' + client);
});

server.on('client_on', function(client) {
    console.log('client on ', client);
});

server.on('client_of', function(client) {
    console.log('client off ', client);
});

server.on('error', function(err) {
    console.log(err);
});

server.on('close', function() {
    console.log('server closed');
});

server.listen();// start to listening
```

and connect using command from bash:

```
nc localhost 81
```

app.js throw below error:

```
timers.js:156
    throw new TypeError('msecs must be a number');
          ^
TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:156:11)
    at Socket.setTimeout (net.js:337:12)
    at Server.handler (/home/1111hui/public_html/pdf/node_modules/node-netcat/lib/server.js:38:12)
    at Server.emit (events.js:129:20)
    at TCP.onconnection (net.js:1320:8)

```

seems there's bug in server.js

**Comment by joaquimserafim** [comment]
I'll take a look

thanks

**Comment by joaquimserafim** [comment]
is working for me :/
<img width="1280" alt="nc-working" src="https://cloud.githubusercontent.com/assets/2507889/9480370/8d06e34a-4b7a-11e5-970c-e151a5833bb3.png">

**Comment by KingRial** [comment]
I have the same problem using library version "1.4.8" and node "4.0.x".
It seems this the parameter "this._timeout" on this line, is not defined:
https://github.com/joaquimserafim/node-netcat/blob/master/lib/server.js#L45

Still checking the code to find the problem ( it seems related to the "this" reference which is not pointing to the correct stored timeout )
